-- ============================================================
-- BILL GENERATION SCHEMA (C2)
-- For: Annual Bill Auto-Generation — Edge Function Support
-- ============================================================

-- Annual assessment rates table
CREATE TABLE IF NOT EXISTS public.annual_assessment_rates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    year INTEGER NOT NULL UNIQUE,
    regular_rate NUMERIC(12, 2) NOT NULL,
    social_rate NUMERIC(12, 2),
    student_rate NUMERIC(12, 2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Grant access after creating new table (required with RLS)
GRANT INSERT, SELECT, UPDATE ON TABLE public.annual_assessment_rates TO authenticated;

-- Enable RLS
ALTER TABLE public.annual_assessment_rates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Registrars can read rates"
    ON public.annual_assessment_rates FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM profiles
        WHERE id = auth.uid() AND role IN ('registrar', 'financial_registrar', 'super_admin')
    ));

-- Bill records table — generated by edge function
CREATE TABLE IF NOT EXISTS public.bills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    member_id UUID REFERENCES members(id) ON DELETE CASCADE,
    assessment_year INTEGER NOT NULL,
    rate_type TEXT NOT NULL CHECK (rate_type IN ('regular', 'social', 'student')),
    base_amount NUMERIC(12, 2) NOT NULL,
    arrears_brought_forward NUMERIC(12, 2) DEFAULT 0,
    total_due NUMERIC(12, 2) NOT NULL,
    status TEXT DEFAULT 'unpaid' CHECK (status IN ('pending', 'generated', 'billed', 'partially_paid', 'paid')),
    generated_by TEXT, -- edge function name or user email
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Grant access after creating new table (required with RLS)
GRANT INSERT, SELECT, UPDATE ON TABLE public.bills TO authenticated;

-- Enable RLS
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Registrars can read bills"
    ON public.bills FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM profiles
        WHERE id = auth.uid() AND role IN ('registrar', 'financial_registrar', 'super_admin')
    ));

-- Index for year-based queries
CREATE INDEX IF NOT EXISTS idx_bills_year_status ON bills (assessment_year, status);

-- Bill generation log for tracking runs
CREATE TABLE IF NOT EXISTS public.bill_generation_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_date TIMESTAMPTZ DEFAULT NOW(),
    year_generated INTEGER NOT NULL,
    members_processed INTEGER DEFAULT 0,
    bills_created INTEGER DEFAULT 0,
    status TEXT CHECK (status IN ('running', 'completed', 'failed')),
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Grant access after creating new table (required with RLS)
GRANT INSERT, SELECT, UPDATE ON TABLE public.bill_generation_log TO authenticated;

-- Enable RLS on bill generation log
ALTER TABLE public.bill_generation_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Registrars can read logs"
    ON public.bill_generation_log FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM profiles
        WHERE id = auth.uid() AND role IN ('registrar', 'financial_registrar', 'super_admin')
    ));
