import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { requireFinancialRegistrar } from '@/lib/auth/requireFinancialRegistrar';

// Generate HTML content for payment receipt
function generateReceiptHTML(payment: any): string {
  const memberName = `${payment.first_name || ''} ${payment.surname || ''}`.trim();
  const formattedAmount = `GH¢ ${(parseFloat(payment.amount) || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Payment Receipt</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 40px auto; padding: 20px; }
    .receipt-header { text-align: center; border-bottom: 3px solid #1a2744; padding-bottom: 20px; margin-bottom: 30px; }
    .receipt-number { font-size: 18px; color: #666; margin-top: 8px; }
    .section { margin: 20px 0; }
    .row { display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px dotted #e5e7eb; }
    .label { color: #6b7280; font-size: 14px; }
    .value { font-weight: 600; color: #1f2937; }
    .amount-total { font-size: 24px; font-weight: bold; color: #1a2744; margin-top: 20px; padding: 15px; background: #f8fafc; border-radius: 8px; text-align: center; }
    .footer { text-align: center; margin-top: 60px; font-size: 12px; color: #9ca3af; }
    @media print { body { padding: 0; margin: 0; } .no-print { display: none; } }
  </style>
</head>
<body>
  <div class="receipt-header">
    <h1 style="margin: 0; color: #1a2744;">KSJI Receipt</h1>
    <div class="receipt-number">Receipt No. ${payment.receipt_number || 'N/A'}</div>
  </div>

  <div class="section">
    <div class="row"><span class="label">Member Name</span><span class="value">${memberName}</span></div>
    <div class="row"><span class="label">Payment Date</span><span class="value">${new Date(payment.payment_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span></div>
    <div class="row"><span class="label">Assessment Year</span><span class="value">${payment.year || 'N/A'}</span></div>
  </div>

  <div class="amount-total">${formattedAmount}</div>

  <div style="margin-top: 30px;">
    <button onclick="window.print()" class="no-print" style="padding: 12px 32px; background: #1a2744; color: white; border: none; cursor: pointer; font-size: 16px; border-radius: 6px;">Print Receipt</button>
  </div>

  <div class="footer">
    Generated by KSJI Member Portal<br>
    ${new Date().toLocaleString('en-US')}
  </div>
</body>
</html>`;
}

// GET /api/receipt?id=xxx - Return HTML receipt for printing
export async function GET(request: NextRequest) {
  try {
    await requireFinancialRegistrar();

    const supabase = createClient();
    const searchParams = request.nextUrl.searchParams;
    const paymentId = searchParams.get('id');

    if (!paymentId) {
      return NextResponse.json({ error: 'Payment ID required' }, { status: 400 });
    }

    // Fetch payment with member details
    const { data: payment } = await supabase
      .from('financial_payments')
      .select('*')
      .eq('id', paymentId)
      .single();

    if (!payment) {
      return NextResponse.json({ error: 'Payment not found' }, { status: 404 });
    }

    // Calculate receipt sequence number from member's other payments
    const { data: memberPayments }: any[] = await supabase
      .from('financial_payments')
      .select('id, payment_date')
      .eq('member_id', payment.member_id)
      .order('payment_date', { ascending: true });

    // Receipt number is 1-based position in sequence for this member
    const receiptIndex = memberPayments?.findIndex((p: any) => p.id === paymentId) ?? 0;
    const yearPrefix = new Date(payment.payment_date).getFullYear();
    const receiptNum = `RCP-${yearPrefix}-${String(receiptIndex + 1).padStart(4, '0')}`;

    // Attach to payment object for template
    (payment as any).receipt_number = receiptNum;

    const html = generateReceiptHTML(payment);

    return new NextResponse(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html',
        'Cache-Control': 'no-store, no-cache',
      },
    });
  } catch (error) {
    console.error('Receipt generation error:', error);
    return NextResponse.json({ error: 'Failed to generate receipt' }, { status: 500 });
  }
}
