import Link from 'next/link';
import { Member } from '@/types/member';
function value(v?: string | null) { return v && String(v).trim() ? v : '—'; }
export default function MemberSummaryCard({ member, editHref='/me/edit', showOwner=false }: { member: Member | null; editHref?: string; showOwner?: boolean }) {
  if (!member) return <div style={card}><h3 style={{ marginTop:0 }}>No member record found</h3><p style={{ color:'#53657d' }}>Your account exists, but your main member record has not been created yet.</p></div>;
  return <div style={card}><div style={{ display:'flex', justifyContent:'space-between', gap:16, alignItems:'start', flexWrap:'wrap' }}><div><h2 style={{ margin:'0 0 8px' }}>{[member.title, member.first_name, member.other_names, member.surname].filter(Boolean).join(' ') || 'Unnamed member'}</h2><p style={{ margin:0, color:'#53657d' }}>{value(member.email)} · {value(member.phone || member.mobile)}</p></div><Link href={editHref} style={{ textDecoration:'none', background:'#10233f', color:'#fff', padding:'10px 14px', borderRadius:10, fontWeight:700 }}>Edit main record</Link></div><div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))', gap:16, marginTop:20 }}><Field label='Date of birth' value={value(member.date_of_birth)} /><Field label='Nationality' value={value(member.nationality)} /><Field label='Home region' value={value(member.home_region)} /><Field label='Marital status' value={value(member.marital_status)} /><Field label='Employment' value={value(member.emp_status)} /><Field label='Occupation' value={value(member.occupation)} /><Field label='Workplace' value={value(member.workplace)} /><Field label='Date joined' value={value(member.date_joined)} /></div></div>;
}
function Field({ label, value }: { label:string; value:string }) { return <div><div style={{ fontSize:12, color:'#53657d', marginBottom:4 }}>{label}</div><div style={{ fontWeight:600 }}>{value}</div></div>; }
const card: React.CSSProperties={ background:'#fff', padding:20, borderRadius:16, boxShadow:'0 8px 24px rgba(16,35,63,0.08)' };
