'use client';
import React, { useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { EmergencyContactRecord } from '@/types/emergencyContact';
export default function EmergencyContactsEditor({ memberId, initialContacts }: { memberId:string; initialContacts: EmergencyContactRecord[] }) {
  const supabase=createClient(); const [contacts, setContacts]=useState<EmergencyContactRecord[]>(initialContacts.length ? initialContacts : [{ contact_name:'', relationship:'', phone1:'', phone2:'' }]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  function update(index:number,key:keyof EmergencyContactRecord,value:string){ setContacts(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item)); }
  async function handleSave(){ setBusy(true); setError(null); setMessage(null); const existingIds=initialContacts.filter(c=>c.id).map(c=>c.id) as string[]; const currentIds=contacts.filter(c=>c.id).map(c=>c.id) as string[]; const toDelete=existingIds.filter(id=>!currentIds.includes(id)); if(toDelete.length) await supabase.from('emergency_contacts').delete().in('id', toDelete); for(const contact of contacts){ const payload={...contact, member_id:memberId}; const result = contact.id ? await supabase.from('emergency_contacts').update(payload).eq('id', contact.id).select().single() : await supabase.from('emergency_contacts').insert(payload).select().single(); if(result.error){ setError(result.error.message); setBusy(false); return; } } setMessage('Emergency contacts saved.'); setBusy(false); window.location.reload(); }
  return <div style={cardStyle}><div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}><h2 style={{ margin:0 }}>Emergency contacts</h2><button type='button' onClick={()=>setContacts(items=>[...items,{ contact_name:'', relationship:'', phone1:'', phone2:'' }])} style={secondaryButton}>Add contact</button></div>{contacts.map((contact,index)=><div key={contact.id || index} style={subCardStyle}><div style={gridStyle}><Field label='Name' value={contact.contact_name || ''} onChange={v=>update(index,'contact_name',v)} /><Field label='Relationship' value={contact.relationship || ''} onChange={v=>update(index,'relationship',v)} /><Field label='Phone 1' value={contact.phone1 || ''} onChange={v=>update(index,'phone1',v)} /><Field label='Phone 2' value={contact.phone2 || ''} onChange={v=>update(index,'phone2',v)} /></div><button type='button' onClick={()=>setContacts(items=>items.filter((_,i)=>i!==index))} style={dangerButton}>Remove</button></div>)}<div style={{ display:'flex', gap:12, alignItems:'center', flexWrap:'wrap' }}><button type='button' onClick={handleSave} disabled={busy} style={primaryButton}>{busy ? 'Saving…' : 'Save emergency contacts'}</button>{message?<span style={{ color:'#1f6f43' }}>{message}</span>:null}{error?<span style={{ color:'crimson' }}>{error}</span>:null}</div></div>;
}
function Field({ label, value, onChange }: { label:string; value:string; onChange:(value:string)=>void }) { return <label style={{ display:'grid', gap:6 }}><span style={labelStyle}>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} style={inputStyle} /></label>; }
const cardStyle: React.CSSProperties={ background:'#fff', padding:20, borderRadius:16, boxShadow:'0 8px 24px rgba(16,35,63,0.08)', display:'grid', gap:16 }; const subCardStyle: React.CSSProperties={ padding:14, border:'1px solid #dce4ee', borderRadius:12, display:'grid', gap:12 }; const gridStyle: React.CSSProperties={ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))', gap:12 }; const labelStyle: React.CSSProperties={ fontSize:12, color:'#53657d', fontWeight:700 }; const inputStyle: React.CSSProperties={ padding:'11px 12px', borderRadius:10, border:'1px solid #cfd8e3', fontSize:14 }; const primaryButton: React.CSSProperties={ padding:'12px 16px', borderRadius:10, border:0, background:'#10233f', color:'#fff', fontWeight:700, cursor:'pointer' }; const secondaryButton: React.CSSProperties={ padding:'10px 14px', borderRadius:10, border:'1px solid #cfd8e3', background:'#fff', cursor:'pointer' }; const dangerButton: React.CSSProperties={ padding:'9px 12px', borderRadius:10, border:'1px solid #f0c9c9', color:'#8a1f1f', background:'#fff5f5', cursor:'pointer', justifySelf:'start' };
